### ISSUE TITLE
Error when filtering data for indicator_total_year

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/trias#20]
When making the natuurindicatoren we want to use only the data from the flemish region. e.a. create this  filter:  data <- data %>% filter(locality == "Flemish Region") before using the indicator_total_year function from trias@add_functions_checklist_indicators -branch.

This however prompts an error message 

pls fix this

**Comment by damianooldoni** [comment]
The error we got this morning was the following:
```r
facet_column <- "Kingdom"
data <- data %>% filter(locality == "Flemish Region")
indicator_total_year(data, facet_column = facet_column)
Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn, : length of 'dimnames' [2] not equal to array extent
```
I was in the meantime updating input data (as generated by new version of pipeline `./src/_build_checklist_indicators.Rmd` in `trias-project/repo@pathways` (now with data from six checklist instead of three) and graphic indicator related functions as well. So, probably it was a question of corrupted `trias` package or other local issues on my laptop.
Even using old version of `data` I don't get any error anymore:
```r
library(readr)
filename <- "https://raw.githubusercontent.com/trias-project/pipeline/fcd8382bddffe97fe72900b5da69b293b733a8d3/data/interim/test_data_output_checklist_indicators.tsv"
data_old <- read_tsv(filename)
data_old <- data_old %>% filter(locality == "Flemish Region")
indicator_total_year(data_old, facet_column = facet_column)
```

Could you please try again? For example by running the pipeline `./src/indicator_cumulative_number.Rmd` in `trias-project/pipeline@pathways`?

In case bug disappeared comment and close. Otherwise, please let me know.

**Comment by damianooldoni** [comment]
@SanderDevisscher: I think this can be closed. Could you please check it  if you have time? Thanks.
